language: node_js
node_js:
    - "0.10"
before_script:
      - 'npm install -g grunt-cli'
notifications:
  hipchat: 
    - secure: "QyQcmemZvaHVYLg8hSS6xwfvzzcMhrlKB2C9ihKXzm+QwHMPsOqWHz8rtDtQVc5fwsalaP2rscbIOzyxKxPfh3xMJCkogOBlSPTmOqKv41yZu02g3Btnjaeu47Mb5wMqwAYib246sk1TP9cTf9zulLQtGAcOeujv69LyF3uIREg="
